export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_BEST_SELLERS_PENDING = "REQUEST_BEST_SELLERS_PENDING";
export const REQUEST_BEST_SELLERS_SUCCESS ="REQUEST_BEST_SELLERS_SUCCESS";
export const REQUEST_BEST_SELLERS_FAILED = "REQUEST_BEST_SELLERS_FAILED";

