export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const CHANGE_DATE = "CHANGE DATE";

export const REQUEST_BOOKS_PENDING = "REQUEST_BOOKS_PENDING";
export const REQUEST_BOOKS_SUCCESS = "REQUEST_BOOKS_SUCCESS";
export const REQUEST_BOOKS_FAILED = "REQUEST_BOOKS_FAILED";

export const FLIP_CARD = "FLIP_CARD";
